/*
 * Alăng Quân Sỹ
 * PD09903
 */
package com.mycompany.ui;

import com.mycompany.utils.Auth;
import com.mycompany.utils.Image;
import com.mycompany.utils.MsgBox;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Just Share
 */
public class QuanLyXeMay extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyXeMay
     */
    public QuanLyXeMay() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTenNguoiDangNhap = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bntDangXuat = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblDongHo = new javax.swing.JLabel();
        btnQuanLyTaiKhoan = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnQuanLyKhachHang = new javax.swing.JButton();
        btnBaoVe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniTaiKhoann = new javax.swing.JMenuItem();
        mniNhanVien = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        mniTheCuoc = new javax.swing.JMenuItem();
        mnuBaoVe = new javax.swing.JMenu();
        mnuKhachHang = new javax.swing.JMenu();
        mniQuanLyXeMay = new javax.swing.JMenuItem();
        mniMuaThe = new javax.swing.JMenuItem();
        mniLichSu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý trạm giữ xe");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTenNguoiDangNhap.setText("Xin chào: Mr Beast");

        lblVaiTro.setText("Vai trò: Quản lý");

        jLabel5.setText("Thông tin:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenNguoiDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenNguoiDangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVaiTro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bntDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/switch.png"))); // NOI18N
        bntDangXuat.setText("Đăng xuất");
        bntDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDangXuatActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/rising.png"))); // NOI18N
        jButton4.setText("Nạp tiền");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/keyword.png"))); // NOI18N
        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntDangXuat)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/clock.png"))); // NOI18N
        lblDongHo.setText("00:00:00 AM");

        btnQuanLyTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/avatar.png"))); // NOI18N
        btnQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyTaiKhoanActionPerformed(evt);
            }
        });

        btnQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/grouping.png"))); // NOI18N
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });

        btnQuanLyKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/client.png"))); // NOI18N
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });

        btnBaoVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/guard.png"))); // NOI18N
        btnBaoVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoVeActionPerformed(evt);
            }
        });

        jMenu1.setText("Quản lý");

        mniTaiKhoann.setText("Tài khoản");
        mniTaiKhoann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoannActionPerformed(evt);
            }
        });
        jMenu1.add(mniTaiKhoann);

        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(mniNhanVien);

        mniKhachHang.setText("khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        jMenu1.add(mniKhachHang);

        mniTheCuoc.setText("Thẻ cước");
        mniTheCuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTheCuocActionPerformed(evt);
            }
        });
        jMenu1.add(mniTheCuoc);

        jMenuBar1.add(jMenu1);

        mnuBaoVe.setText("Bảo vệ");
        mnuBaoVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuBaoVeMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuBaoVe);

        mnuKhachHang.setText("Khách hàng");

        mniQuanLyXeMay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/motorbike.png"))); // NOI18N
        mniQuanLyXeMay.setText("Quản lý xe máy");
        mniQuanLyXeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyXeMayActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniQuanLyXeMay);

        mniMuaThe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/credit-card.png"))); // NOI18N
        mniMuaThe.setText("Mua thẻ xe");
        mniMuaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMuaTheActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniMuaThe);

        mniLichSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/history-book.png"))); // NOI18N
        mniLichSu.setText("Lịch sữ xe ra - vào");
        mniLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLichSuActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniLichSu);

        jMenuBar1.add(mnuKhachHang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuanLyTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyNhanVien)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyKhachHang)
                .addGap(18, 18, 18)
                .addComponent(btnBaoVe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuanLyTaiKhoan)
                            .addComponent(btnQuanLyNhanVien)
                            .addComponent(btnQuanLyKhachHang)))
                    .addComponent(btnBaoVe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        openQuanLyTaiKhoan();
    }//GEN-LAST:event_btnQuanLyTaiKhoanActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        openQuanLyNhanVien();
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhachHangActionPerformed
        // TODO add your handling code here:
        openQuanLyKhachHang();
    }//GEN-LAST:event_btnQuanLyKhachHangActionPerformed

    private void mniTaiKhoannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoannActionPerformed
        // TODO add your handling code here:
        openQuanLyTaiKhoan();
    }//GEN-LAST:event_mniTaiKhoannActionPerformed

    private void mniQuanLyXeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyXeMayActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniQuanLyXeMayActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        openQuanLyNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        // TODO add your handling code here:
        openQuanLyKhachHang();
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mniTheCuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTheCuocActionPerformed
        // TODO add your handling code here:
        openQuanLyGoiCuoc();
    }//GEN-LAST:event_mniTheCuocActionPerformed

    private void mniMuaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMuaTheActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniMuaTheActionPerformed

    private void mniLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLichSuActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniLichSuActionPerformed

    private void bntDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDangXuatActionPerformed
        // TODO add your handling code here:
        openDangXuat();
    }//GEN-LAST:event_bntDangXuatActionPerformed

    private void mnuBaoVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuBaoVeMouseClicked
        openQuanLyXeRaVao();
    }//GEN-LAST:event_mnuBaoVeMouseClicked

    private void btnBaoVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoVeActionPerformed
        // TODO add your handling code here:
        openQuanLyXeRaVao();
    }//GEN-LAST:event_btnBaoVeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        openDoiMatKhau();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyXeMay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDangXuat;
    private javax.swing.JButton btnBaoVe;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblTenNguoiDangNhap;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniLichSu;
    private javax.swing.JMenuItem mniMuaThe;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniQuanLyXeMay;
    private javax.swing.JMenuItem mniTaiKhoann;
    private javax.swing.JMenuItem mniTheCuoc;
    private javax.swing.JMenu mnuBaoVe;
    private javax.swing.JMenu mnuKhachHang;
    // End of variables declaration//GEN-END:variables

    private void openQuanLyTaiKhoan() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("quanLy")) {
            new QuanLyTaiKhoanJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void openQuanLyNhanVien() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("quanLy")) {
            new QuanLyNhanVienJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void openQuanLyKhachHang() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("quanLy")) {
            new QuanLyKhachHangJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void openQuanLyGoiCuoc() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("quanLy")) {
            new QuanLyGoiCuocJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void openQuanLyXeRaVao() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("baoVe")) {
            new BaoVeJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void openKhachHang() {
        if (Auth.quyenTruyCap().equalsIgnoreCase("khachHang")) {
            new KhachHangJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Bạn không có quyền truy cập!");
        }
    }

    private void init() {
        setLocationRelativeTo(null);
        setIconImage(Image.getAppIcon());
        new ChaoJDialog(this, true).setVisible(true);
        new LoginJDialog(this, true).setVisible(true);

        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
        }).start();

        capNhatTenHienThi();
    }

    private void openDangXuat() {
        Auth.clear();
        new LoginJDialog(this, true).setVisible(true);
        capNhatTenHienThi();
    }

    private void capNhatTenHienThi() {
        lblTenNguoiDangNhap.setText("Xin chào: " + Auth.user.getTenDangNhap());
        String vaiTro;
        if (Auth.user.getQuyen() == 1) {
            vaiTro = "Chức vụ: Quản lý";
        } else if (Auth.user.getQuyen() == 2) {
            vaiTro = "Chức vụ: Bảo vệ";
        } else {
            vaiTro = "Vai trò: Khách hàng";
        }
        lblVaiTro.setText(vaiTro);
    }

    private void openDoiMatKhau() {
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }
}
