/*
 * Alăng Quân Sỹ
 * PD09903
 */
package com.mycompany.ui;

/**
 *
 * @author Just Share
 */
public class QuanLyXeMay extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyXeMay
     */
    public QuanLyXeMay() {
        initComponents();
        setLocationRelativeTo(null);
        new ChaoJDialog(this, true).setVisible(true);
        new LoginJDialog(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bntDangXuat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniTaiKhoann = new javax.swing.JMenuItem();
        mniNhanVien = new javax.swing.JMenuItem();
        mniKhachHang = new javax.swing.JMenuItem();
        mniTheCuoc = new javax.swing.JMenuItem();
        mnuBaoVe = new javax.swing.JMenu();
        mnuKhachHang = new javax.swing.JMenu();
        mniQuanLyXeMay = new javax.swing.JMenuItem();
        mniMuaThe = new javax.swing.JMenuItem();
        mniLichSu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Xin chào: Mr Beast");

        jLabel4.setText("Vai trò: Quản lý");

        jLabel5.setText("Thông tin:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bntDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/switch.png"))); // NOI18N
        bntDangXuat.setText("Đăng xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntDangXuat)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bntDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/clock.png"))); // NOI18N
        jLabel6.setText("00:00:00 AM");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/avatar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/grouping.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/icon/client.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Quản lý");

        mniTaiKhoann.setText("Tài khoản");
        mniTaiKhoann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoannActionPerformed(evt);
            }
        });
        jMenu1.add(mniTaiKhoann);

        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(mniNhanVien);

        mniKhachHang.setText("khách hàng");
        mniKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhachHangActionPerformed(evt);
            }
        });
        jMenu1.add(mniKhachHang);

        mniTheCuoc.setText("Thẻ cước");
        mniTheCuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTheCuocActionPerformed(evt);
            }
        });
        jMenu1.add(mniTheCuoc);

        jMenuBar1.add(jMenu1);

        mnuBaoVe.setText("Bảo vệ");
        mnuBaoVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBaoVeActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuBaoVe);

        mnuKhachHang.setText("Khách hàng");

        mniQuanLyXeMay.setText("Quản lý xe máy");
        mniQuanLyXeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniQuanLyXeMayActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniQuanLyXeMay);

        mniMuaThe.setText("Mua thẻ xe");
        mniMuaThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMuaTheActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniMuaThe);

        mniLichSu.setText("Lịch sữ xe ra - vào");
        mniLichSu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLichSuActionPerformed(evt);
            }
        });
        mnuKhachHang.add(mniLichSu);

        jMenuBar1.add(mnuKhachHang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new QuanLyTaiKhoanJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new QuanLyNhanVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new QuanLyKhackHangJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mniTaiKhoannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoannActionPerformed
        // TODO add your handling code here:
        openQuanLyTaiKhoan();
    }//GEN-LAST:event_mniTaiKhoannActionPerformed

    private void mniQuanLyXeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniQuanLyXeMayActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniQuanLyXeMayActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        // TODO add your handling code here:
        openQuanLyNhanVien();
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhachHangActionPerformed
        // TODO add your handling code here:
        openQuanLyKhachHang();
    }//GEN-LAST:event_mniKhachHangActionPerformed

    private void mniTheCuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTheCuocActionPerformed
        // TODO add your handling code here:
        openQuanLyGoiCuoc();
    }//GEN-LAST:event_mniTheCuocActionPerformed

    private void mnuBaoVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBaoVeActionPerformed
        // TODO add your handling code here:
        openQuanLyXeRaVao();
    }//GEN-LAST:event_mnuBaoVeActionPerformed

    private void mniMuaTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMuaTheActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniMuaTheActionPerformed

    private void mniLichSuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLichSuActionPerformed
        // TODO add your handling code here:
        openKhachHang();
    }//GEN-LAST:event_mniLichSuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyXeMay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyXeMay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDangXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem mniKhachHang;
    private javax.swing.JMenuItem mniLichSu;
    private javax.swing.JMenuItem mniMuaThe;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniQuanLyXeMay;
    private javax.swing.JMenuItem mniTaiKhoann;
    private javax.swing.JMenuItem mniTheCuoc;
    private javax.swing.JMenu mnuBaoVe;
    private javax.swing.JMenu mnuKhachHang;
    // End of variables declaration//GEN-END:variables

    private void openQuanLyTaiKhoan() {
       new QuanLyTaiKhoanJDialog(this, true).setVisible(true);
    }

    private void openQuanLyNhanVien() {
        new QuanLyNhanVienJDialog(this, true).setVisible(true);
    }

    private void openQuanLyKhachHang() {
       new QuanLyKhackHangJDialog(this, true).setVisible(true);
    }

    private void openQuanLyGoiCuoc() {
        new QuanLyGoiCuoiJDialog(this, true).setVisible(true);
    }

    private void openQuanLyXeRaVao() {
        new BaoVeJDialog(this, true).setVisible(true);
    }

    private void openKhachHang() {
        new KhachHangJDialog(this, true).setVisible(true);
    }
}
